remote_theme: pmarsceill/just-the-docs
collections:
  intro:
    permalink: "/:collection/:path/"
    directory: intro
    output: true
  docs:
    permalink: "/:collection/:path/"
    directory: docs
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    intro:
      name: Introduction
    docs:
      name: Documentation
    tutorials:
      name: Tutorials
